# Generated by Django 5.0.2 on 2024-03-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='blank_profile_picture.jpg', upload_to='profile_images'),
        ),
    ]
